-- 1. Modules Table
create table if not exists public.modules (
  id bigint generated by default as identity primary key,
  title text not null,
  order_index integer
);

-- 2. Lessons Table
create table if not exists public.lessons (
  id text primary key, -- Keeping text ID to match local UUID/String IDs
  module_id bigint references public.modules(id) on delete cascade,
  title text not null,
  description text,
  theory text, -- Markdown content
  status text default 'locked',
  order_index integer
);

-- 3. Lesson Dependencies
create table if not exists public.lesson_dependencies (
  lesson_id text references public.lessons(id) on delete cascade,
  prerequisite_id text references public.lessons(id) on delete cascade,
  primary key (lesson_id, prerequisite_id)
);

-- 4. Exercises Table
create table if not exists public.exercises (
  id bigint generated by default as identity primary key,
  lesson_id text references public.lessons(id) on delete cascade,
  type text not null,
  instruction text,
  content jsonb, -- Using JSONB for structured content
  order_index integer
);

-- 5. Enable RLS
alter table public.modules enable row level security;
alter table public.lessons enable row level security;
alter table public.lesson_dependencies enable row level security;
alter table public.exercises enable row level security;

-- 6. Public Read Policies
create policy "Public read access for modules" on public.modules for select using (true);
create policy "Public read access for lessons" on public.lessons for select using (true);
create policy "Public read access for dependencies" on public.lesson_dependencies for select using (true);
create policy "Public read access for exercises" on public.exercises for select using (true);
